import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { db } from '../firebase';
import { writeBatch, doc, collection, serverTimestamp, Timestamp } from 'firebase/firestore';
import { Database, Loader2, CheckCircle2 } from 'lucide-react';
import { Machine } from '../types';
import { OCCUPATIONS } from '../data/occupational-matrix';
import { CLINICAL_FLAGS_MATRIX } from '../data/clinical-matrix';

interface PresentationDataSeederProps {
  machines: Machine[];
}

export function PresentationDataSeeder({ machines }: PresentationDataSeederProps) {
  const [isSeeding, setIsSeeding] = useState(false);
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState<string | null>(null);

  const MOCK_FIRST_NAMES = ["James", "Maria", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Nancy", "Daniel", "Margaret", "Matthew", "Lisa", "Anthony", "Betty", "Donald", "Dorothy", "Mark", "Sandra"];
  const MOCK_LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson"];
  
  const generateRandomClient = () => {
    const firstName = MOCK_FIRST_NAMES[Math.floor(Math.random() * MOCK_FIRST_NAMES.length)];
    const lastName = MOCK_LAST_NAMES[Math.floor(Math.random() * MOCK_LAST_NAMES.length)];
    const age = Math.floor(Math.random() * (80 - 35 + 1)) + 35;
    const isActive = Math.random() < 0.85;
    const occupation = OCCUPATIONS[Math.floor(Math.random() * OCCUPATIONS.length)];

    let clinicalFlags: string[] = [];
    const flagRoll = Math.random();
    if (flagRoll > 0.95) { // 5% chance of 2 flags
      const f1 = CLINICAL_FLAGS_MATRIX[Math.floor(Math.random() * CLINICAL_FLAGS_MATRIX.length)].id;
      const f2 = CLINICAL_FLAGS_MATRIX[Math.floor(Math.random() * CLINICAL_FLAGS_MATRIX.length)].id;
      clinicalFlags = Array.from(new Set([f1, f2]));
    } else if (flagRoll > 0.80) { // 15% chance of 1 flag
      clinicalFlags = [CLINICAL_FLAGS_MATRIX[Math.floor(Math.random() * CLINICAL_FLAGS_MATRIX.length)].id];
    } // 80% chance of 0 flags

    const hasMinorHistory = Math.random() < 0.2;

    return {
      firstName,
      lastName,
      dateOfBirth: new Date(new Date().getFullYear() - age, Math.floor(Math.random() * 12), Math.floor(Math.random() * 28)).toISOString().split('T')[0],
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${Math.floor(Math.random()*1000)}@example.com`,
      phone: `555-${Math.floor(Math.random() * 900 + 100)}-${Math.floor(Math.random() * 9000 + 1000)}`,
      gender: Math.random() > 0.5 ? 'Male' : 'Female',
      status: isActive ? 'Active' : 'Inactive' as any,
      globalNotes: 'Generated by Presentation Seeder for load testing.',
      occupationId: occupation.id,
      clinicalFlags,
      orthopedicHistory: hasMinorHistory ? 'Minor joint discomfort reported occasionally. Monitor range of motion.' : ''
    };
  };

  const seedPresentationData = async () => {
    if (!machines || machines.length === 0) {
      alert("No machines available to seed data. Please ensure machines are loaded.");
      return;
    }
    
    setIsSeeding(true);
    setProgress(0);
    setStatus("Forging 100 Clients in Database...");

    try {
      const TOTAL_CLIENTS = 100;
      const CHUNK_SIZE = 50; // Keep under 500 ops per batch
      
      let allWrites: any[] = [];
      const now = Date.now();

      for (let i = 0; i < TOTAL_CLIENTS; i++) {
        const clientRef = doc(collection(db, 'clients'));
        const clientData = generateRandomClient();
        
        allWrites.push({
          type: 'set',
          ref: clientRef,
          data: {
            ...clientData,
            createdAt: serverTimestamp(),
            updatedAt: serverTimestamp()
          }
        });

        // 2. Routine Assignment
        const hasB = Math.random() < 0.7; // 70% have A & B
        
        const availableMachines = [...machines].sort(() => 0.5 - Math.random());
        const routineAMachines = availableMachines.slice(0, Math.floor(Math.random() * 3) + 6); // 6 to 8 machines
        const routineBMachines = hasB ? [...availableMachines].sort(() => 0.5 - Math.random()).slice(0, Math.floor(Math.random() * 3) + 6) : [];

        const routineARef = doc(collection(db, 'routines'));
        allWrites.push({
          type: 'set',
          ref: routineARef,
          data: {
            clientId: clientRef.id,
            name: "Routine A",
            type: "A",
            exercises: routineAMachines.map((m, idx) => ({
              machineId: m.id,
              order: idx
            })),
            notes: "Seeder Generated",
            createdAt: serverTimestamp()
          }
        });

        let routineBRef: any = null;
        if (hasB) {
          routineBRef = doc(collection(db, 'routines'));
          allWrites.push({
            type: 'set',
            ref: routineBRef,
            data: {
              clientId: clientRef.id,
              name: "Routine B",
              type: "B",
              exercises: routineBMachines.map((m, idx) => ({
                machineId: m.id,
                order: idx
              })),
              notes: "Seeder Generated",
              createdAt: serverTimestamp()
            }
          });
        }

        // 3. Historical Session Generation
        const numSessions = Math.floor(Math.random() * 51) + 10; // 10 to 60 sessions
        let sessionDate = new Date();
        
        // Track weights for progressive overload
        const machineWeights: Record<string, number> = {};

        for (let s = numSessions - 1; s >= 0; s--) {
          // Space alternating every 3 and 4 days
          const daysToSubtract = s % 2 === 0 ? 3 : 4;
          sessionDate.setDate(sessionDate.getDate() - daysToSubtract);
          
          const isRoutineA = !hasB || (s % 2 === 0);
          const currentRoutineMachines = isRoutineA ? routineAMachines : routineBMachines;
          const currentRoutineRef = isRoutineA ? routineARef : routineBRef;

          const sessionRef = doc(collection(db, 'sessions'));
          
          // Generate logs for this session
          const sessionLogs: any[] = [];
          
          currentRoutineMachines.forEach((machine) => {
             if (!machineWeights[machine.id!]) {
                // Initial weight 30-60
                machineWeights[machine.id!] = Math.floor(Math.random() * 31) + 30;
             } else {
                // 30% chance weight increases by 2 lbs
                if (Math.random() < 0.3) {
                   machineWeights[machine.id!] += 2;
                }
             }
             
             // Quality heavily favor 3 and 2, rarely 1
             const qualityRoll = Math.random();
             const repQuality = qualityRoll > 0.95 ? 1 : (qualityRoll > 0.4 ? 3 : 2);
             const reps = Math.floor(Math.random() * 6) + 5; // 5 to 10
             
             const logRef = doc(collection(db, 'exerciseLogs'));
             allWrites.push({
                type: 'set',
                ref: logRef,
                data: {
                   clientId: clientRef.id,
                   sessionId: sessionRef.id,
                   machineId: machine.id,
                   routineId: currentRoutineRef.id,
                   weight: machineWeights[machine.id!].toString(),
                   reps: reps.toString(),
                   pinPosition: "1",
                   padPosition: "1",
                   seatPosition: "1",
                   repQuality: repQuality,
                   notes: '',
                   createdAt: Timestamp.fromDate(new Date(sessionDate))
                }
             });
          });

          allWrites.push({
             type: 'set',
             ref: sessionRef,
             data: {
               clientId: clientRef.id,
               trainerId: "seeder-mock-trainer",
               trainerName: "System Seeder",
               routineId: currentRoutineRef.id,
               date: Timestamp.fromDate(new Date(sessionDate)),
               startTime: Timestamp.fromDate(new Date(sessionDate)),
               endTime: Timestamp.fromDate(new Date(sessionDate.getTime() + 20 * 60000)), // 20 min later
               durationMinutes: 20,
               notes: "Auto-generated session",
               status: 'completed',
               type: 'Routine',
               isPreSessionBriefingComplete: true,
               createdAt: Timestamp.fromDate(new Date(sessionDate)) // Add createdAt for App.tsx query
             }
          });
        }
      }

      // Execute Batches Safely
      let processed = 0;
      while (processed < allWrites.length) {
         setStatus(`Committing batch ${Math.floor(processed / 500) + 1} of ${Math.ceil(allWrites.length / 500)}...`);
         const batch = writeBatch(db);
         const slice = allWrites.slice(processed, processed + 500);
         
         slice.forEach(op => {
            batch.set(op.ref, op.data);
         });
         
         await batch.commit();
         processed += slice.length;
         
         setProgress(Math.floor((processed / allWrites.length) * 100));
         
         // Slight delay to respect Firebase quotas
         await new Promise(resolve => setTimeout(resolve, 1000));
      }

      setStatus(`Successfully forged 100 clients!`);
      setTimeout(() => setStatus(null), 5000);

    } catch (error) {
      console.error("Error seeding presentation data:", error);
      setStatus("Error generating data. Check console.");
    } finally {
      setIsSeeding(false);
    }
  };

  return (
    <Card className="border-2 border-slate-700 bg-slate-900 overflow-hidden mt-8">
      <CardHeader className="bg-slate-800/80 border-b border-slate-700 p-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[#F06C22]/20 flex items-center justify-center">
            <Database className="w-5 h-5 text-[#F06C22]" />
          </div>
          <div>
            <CardTitle className="text-xl font-black uppercase text-white tracking-widest leading-tight">
              Presentation Data Seeder
            </CardTitle>
            <CardDescription className="text-slate-400 font-medium uppercase text-[10px] tracking-widest mt-1">
              Stress test calculations and DB reads
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-8 space-y-6">
        <div className="p-5 bg-slate-950/50 rounded-2xl border border-slate-800 space-y-3">
          <p className="text-sm font-medium text-slate-300 leading-relaxed">
            This utility will generate <strong>100 highly realistic mock clients</strong> to test rendering performance, data matrices, and Firebase limits. 
          </p>
          <ul className="text-[11px] font-bold text-slate-500 uppercase tracking-widest space-y-1">
            <li>• Valid A/B 6-8 machine routines</li>
            <li>• 10-60 historical sessions per client</li>
            <li>• 2x/week strict frequency spacing</li>
            <li>• Gradual 2lb progressive overload curve</li>
          </ul>
        </div>

        <div className="flex flex-col gap-4">
          <Button
            onClick={seedPresentationData}
            disabled={isSeeding}
            className="w-full h-14 bg-[#0A2E46] hover:bg-[#0A2E46]/90 border-2 border-[#38BDF8] text-[#38BDF8] hover:text-white rounded-2xl font-black uppercase tracking-[0.2em] shadow-lg shadow-sky-900/20 transition-all text-sm"
          >
            {isSeeding ? (
              <span className="flex items-center gap-2">
                <Loader2 className="w-4 h-4 animate-spin" />
                {progress > 0 ? `${progress}% Completed` : 'Forging Data...'}
              </span>
            ) : (
              <span className="flex items-center gap-2">
                <Database className="w-4 h-4" />
                SEEd PRESENTATION DATA
              </span>
            )}
          </Button>
          
          {status && (
            <div className="p-4 rounded-xl bg-slate-800 border border-slate-700 flex items-center gap-3">
              {isSeeding ? (
                <Loader2 className="w-4 h-4 text-[#38BDF8] animate-spin shrink-0" />
              ) : (
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              )}
              <span className="text-xs font-bold text-slate-300">
                {status}
              </span>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
